version: '3.9'

services:
  database:
    image: postgres
    container_name: database_racer
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12904170
      - POSTGRES_DB=racer
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: gameracer
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local